### PR TITLE
Add Traditional Chinese

### PR DESCRIPTION
**Pull request by cracky5322**

### CODE REVIEW

**Comment by zelixdxin** [comment]
I want to repair the simplified Chinese translation, please reset setting Translate to reset settings

**Comment by zelixdxin** [comment]
themes, please change it to 皮肤

**Comment by xC3FFF0E** [comment]
I will add this to the new update. As always, thank you @cracky5322 @zelixdxin

**Comment by cracky5322** [comment]
> I want to repair the simplified Chinese translation, please reset setting Translate to 重置设置

Thank you for your help, I made a mistake in setting the traditional Chinese translation error when using the auxiliary tool

**Comment by cracky5322** [comment]
> I want to repair the simplified Chinese translation, please reset setting Translate to 重置设置

Thank you for your help, I made a mistake in setting the traditional Chinese translation error when using the auxiliary tool

**Pull request merged**
